version 0.4.1
AnacondaRecipes/python-poppler-feedstock pull request #1
Opened 2023-09-26 08:46 UTC by M-Waszkiewicz-Anaconda

initial version 0.4.1

[upstream ](https://github.com/cbrunet/python-poppler/tree/v0.4.1)

2023-09-26 12:11 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:46: missing_pip_check: For pypi packages, pip check should be present in the test commands
Errors were found

</details>

2023-09-26 13:13 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:47: missing_pip_check: For pypi packages, pip check should be present in the test commands
Errors were found

</details>

2023-09-26 13:16 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - python
Do we want to ignore_run_exports for python?

2023-09-26 13:16 UTC, skupr-anaconda commented on recipe/meta.yaml
> +  license: GPL-2.0
```suggestion
  license: GPL-2.0-or-later
```

2023-09-26 13:29 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:47: missing_pip_check: For pypi packages, pip check should be present in the test commands
Errors were found

</details>

2023-09-28 21:14 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:47: missing_pip_check: For pypi packages, pip check should be present in the test commands
Errors were found

</details>

2023-09-29 13:55 UTC, skupr-anaconda approved these changes

2023-09-29 13:55 UTC, skupr-anaconda commented on abs.yaml
> +  - https://staging.continuum.io/prefect/fs/poppler-feedstock/pr16/f8c28aa
To be removed before merging and enabling:
```
upload_channels:
  - sfe1ed40
```

2023-09-29 14:05 UTC, cbouss requested changes

2023-09-29 14:05 UTC, cbouss commented on recipe/meta.yaml
> +  dev_url: https://github.com/python-rapidjson/python-rapidjson
```suggestion
  dev_url: https://github.com/cbrunet/python-poppler
```

2023-09-29 14:05 UTC, cbouss commented on recipe/meta.yaml
> +    - meson >=1.0.0
```suggestion
    - meson >=1.1.0
```
https://github.com/cbrunet/python-poppler/blob/v0.4.1/meson.build#L7

2023-09-29 14:05 UTC, cbouss commented on recipe/meta.yaml
> +    - poppler 22.12.0
You should unvendor pybind and add it as a host dependency.
https://github.com/cbrunet/python-poppler/blob/v0.4.1/meson.build#L16

2023-09-29 14:05 UTC, cbouss commented on recipe/meta.yaml
> +    - cmake >=3.18
```suggestion
```
No cmake involved here, this is a meson build.

2023-09-29 14:05 UTC, cbouss commented on recipe/meta.yaml
> +    - ninja       # [win]
```suggestion
```

2023-09-29 14:05 UTC, cbouss commented on recipe/meta.yaml
> +    - pip check # [not win]
```suggestion
    - pip check
```
Or what is the reason for commenting pip check here?

2023-09-29 15:00 UTC, cbouss approved these changes

2023-09-29 17:04 UTC, merged